# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-11 16:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=b'', max_length=250, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name=b'\xd0\x9a\xd1\x83\xd1\x80\xd1\x81')),
            ],
            options={
                'verbose_name': '\u041a\u0443\u0440\u0441 \u0432\u0430\u043b\u044e\u0442',
                'verbose_name_plural': '\u041a\u0443\u0440\u0441\u044b \u0432\u0430\u043b\u044e\u0442',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=b'', max_length=250, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('info', models.TextField(blank=True, default=b'', null=True, verbose_name='\u0418\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044f')),
                ('block', models.BooleanField(default=False, verbose_name='\u0417\u0430\u0431\u043b\u043e\u043a\u0438\u0440\u043e\u0432\u0430\u043d\u043e')),
                ('path', models.CharField(blank=True, default=b'', max_length=250, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('sizefile', models.IntegerField(default=0, verbose_name='\u0420\u0430\u0437\u043c\u0435\u0440 \u0444\u0430\u0439\u043b\u0430')),
                ('upload', models.FileField(blank=True, null=True, upload_to=b'uploads/', verbose_name=b'\xd0\xa4\xd0\xb0\xd0\xb9\xd0\xbb')),
                ('uploadtime', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name=b'\xd0\x94\xd0\xb0\xd1\x82\xd0\xb0 \xd0\xbf\xd0\xbe\xd1\x81\xd0\xbb\xd0\xb5\xd0\xb4\xd0\xbd\xd0\xb5\xd0\xb9 \xd0\xb7\xd0\xb0\xd0\xb3\xd1\x80\xd1\x83\xd0\xb7\xd0\xba\xd0\xb8')),
                ('brand', models.IntegerField(default=0, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('model', models.IntegerField(default=0, verbose_name='\u041c\u043e\u0434\u0435\u043b\u044c')),
                ('articul', models.IntegerField(default=0, verbose_name='\u0410\u0440\u0442\u0438\u043a\u0443\u043b')),
                ('description', models.IntegerField(default=0, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('garantee', models.IntegerField(default=0, verbose_name='\u0413\u0430\u0440\u0430\u043d\u0442\u0438\u044f \u043a\u043e\u043b\u043e\u043d\u043a\u0430')),
                ('garanteemonth', models.IntegerField(default=0, verbose_name='\u0413\u0430\u0440\u0430\u043d\u0442\u0438\u044f \u043c\u0435\u0441\u044f\u0446\u0435\u0432')),
                ('discount', models.IntegerField(default=0, verbose_name='\u0421\u043a\u0438\u0434\u043a\u0430')),
                ('official', models.BooleanField(default=False, verbose_name='\u041e\u0444\u0438\u0446\u0438\u0430\u043b')),
                ('rrc', models.BooleanField(default=False, verbose_name='\u0420\u0420\u0426')),
                ('nal', models.BooleanField(default=False, verbose_name='\u041d\u0430\u043b\u0438\u0447\u0430\u0435')),
                ('nalrow', models.IntegerField(default=0, verbose_name='\u041d\u0430\u043b\u0438\u0447\u0430\u0435 \u0440\u044f\u0434')),
                ('nalsym', models.CharField(blank=True, default=b'', max_length=250, verbose_name='\u041d\u0430\u043b\u0438\u0447\u0430\u0435 \u0441\u0438\u043c\u0432\u043e\u043b')),
                ('currency', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='pricelist.Currency', verbose_name=b'\xd0\x92\xd0\xb0\xd0\xbb\xd1\x8e\xd1\x82\xd0\xb0')),
            ],
            options={
                'verbose_name': '\u041f\u043e\u0441\u0442\u0430\u0432\u0449\u0438\u043a',
                'verbose_name_plural': '\u041f\u043e\u0441\u0442\u0430\u0432\u0449\u0438\u043a\u0438',
            },
        ),
    ]
