# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-12 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='brand',
            field=models.IntegerField(blank=True, default=0, verbose_name='\u0411\u0440\u0435\u043d\u0434'),
        ),
    ]
