# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-12 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0002_auto_20170412_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='price',
            field=models.IntegerField(blank=True, default=0, verbose_name='\u0426\u0435\u043d\u0430 \u043a\u043e\u043b\u043e\u043d\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='articul',
            field=models.IntegerField(blank=True, default=0, verbose_name='\u0410\u0440\u0442\u0438\u043a\u0443\u043b \u043a\u043e\u043b\u043e\u043d\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='brand',
            field=models.IntegerField(blank=True, default=0, verbose_name='\u0411\u0440\u0435\u043d\u0434 \u043a\u043e\u043b\u043e\u043d\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='description',
            field=models.IntegerField(blank=True, default=0, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u043a\u043e\u043b\u043e\u043d\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='discount',
            field=models.IntegerField(blank=True, default=0, verbose_name='\u0421\u043a\u0438\u0434\u043a\u0430 \u043a\u043e\u043b\u043e\u043d\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='garantee',
            field=models.IntegerField(blank=True, default=0, verbose_name='\u0413\u0430\u0440\u0430\u043d\u0442\u0438\u044f \u043a\u043e\u043b\u043e\u043d\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='garanteemonth',
            field=models.IntegerField(blank=True, default=0, verbose_name='\u0413\u0430\u0440\u0430\u043d\u0442\u0438\u044f \u043c\u0435\u0441\u044f\u0446\u0435\u0432 \u043a\u043e\u043b\u043e\u043d\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='model',
            field=models.IntegerField(blank=True, default=0, verbose_name='\u041c\u043e\u0434\u0435\u043b\u044c \u043a\u043e\u043b\u043e\u043d\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='nalrow',
            field=models.IntegerField(blank=True, default=0, verbose_name='\u041d\u0430\u043b\u0438\u0447\u0430\u0435 \u0440\u044f\u0434'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='sizefile',
            field=models.IntegerField(blank=True, default=0, verbose_name='\u0420\u0430\u0437\u043c\u0435\u0440 \u0444\u0430\u0439\u043b\u0430'),
        ),
    ]
