# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-30 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0010_auto_20170530_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileprovider',
            name='garanteemonth',
        ),
        migrations.AddField(
            model_name='provider',
            name='garanteemonth',
            field=models.IntegerField(blank=True, default=0, verbose_name='\u0413\u0430\u0440\u0430\u043d\u0442\u0438\u044f \u043c\u0435\u0441\u044f\u0446\u0435\u0432 \u043f\u043e\u0441\u0442\u0430\u0432\u0449\u0438\u043a'),
        ),
    ]
