# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-30 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0011_auto_20170530_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileprovider',
            name='discount',
        ),
        migrations.AddField(
            model_name='provider',
            name='discount',
            field=models.IntegerField(blank=True, default=0, verbose_name='\u0421\u043a\u0438\u0434\u043a\u0430 \u043a\u043e\u043b\u043e\u043d\u043a\u0430'),
        ),
    ]
