# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-30 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0012_auto_20170530_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileprovider',
            name='content_hash',
            field=models.TextField(blank=True, null=True, verbose_name='Content Hash'),
        ),
    ]
