# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-05 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0013_fileprovider_content_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='dropbox_dir',
            field=models.CharField(blank=True, default=b'', max_length=250, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
    ]
