# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-06 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0015_auto_20170605_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileprovider',
            name='dropbox_file',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='dropbox_dir',
        ),
    ]
