# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-09 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0019_auto_20170607_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileprovider',
            name='sizefile',
        ),
        migrations.RemoveField(
            model_name='fileprovider',
            name='upload',
        ),
    ]
