# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-10 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0022_pricestring_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricestring',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pricelist.Currency', verbose_name=b'\xd0\x92\xd0\xb0\xd0\xbb\xd1\x8e\xd1\x82\xd0\xb0'),
            preserve_default=False,
        ),
    ]
