# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-21 09:46
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name=b'\xd0\x9b\xd0\xbe\xd0\xb3\xd0\xb8\xd0\xbd')),
                ('first_name', models.CharField(max_length=255, verbose_name=b'\xd0\x98\xd0\xbc\xd1\x8f')),
                ('last_name', models.CharField(max_length=255, null=True, verbose_name=b'\xd0\xa4\xd0\xb0\xd0\xbc\xd0\xb8\xd0\xbb\xd0\xb8\xd1\x8f')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name=b'email')),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('whishlist', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'whishlist')),
                ('removed', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'removed')),
                ('removedwithdetails', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'removed with details')),
                ('viewed', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'\xd0\x9f\xd1\x80\xd0\xbe\xd1\x81\xd0\xbc\xd0\xbe\xd1\x82\xd1\x80\xd0\xb5\xd0\xbd\xd0\xbd\xd1\x8b\xd0\xb5')),
                ('emails', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'Emails')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
