# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-26 09:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0007_auto_20161226_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2016, 12, 26, 9, 45, 57, 879082, tzinfo=utc)),
        ),
    ]
