# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-27 08:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0010_auto_20161226_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2016, 12, 27, 8, 59, 1, 1025, tzinfo=utc)),
        ),
    ]
