# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-27 09:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0012_auto_20161227_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2016, 12, 27, 9, 26, 7, 611357, tzinfo=utc)),
        ),
    ]
