# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-02 10:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0018_auto_20161228_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2017, 1, 2, 10, 2, 28, 57400, tzinfo=utc)),
        ),
    ]
