# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-02 15:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0022_auto_20170102_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2017, 1, 2, 15, 0, 27, 697652, tzinfo=utc)),
        ),
    ]
