# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-02 17:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0023_auto_20170102_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2017, 1, 2, 17, 10, 0, 529707, tzinfo=utc)),
        ),
    ]
