# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-04 21:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0024_auto_20170102_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2017, 1, 4, 21, 50, 52, 339115, tzinfo=utc)),
        ),
    ]
