# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-05 10:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0025_auto_20170104_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2017, 1, 5, 10, 23, 48, 924558, tzinfo=utc)),
        ),
    ]
