# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-05 21:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0028_auto_20170105_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2017, 1, 5, 21, 53, 42, 807731, tzinfo=utc)),
        ),
    ]
