# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-09 11:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0037_auto_20170108_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2017, 1, 9, 11, 32, 18, 557992, tzinfo=utc)),
        ),
    ]
