# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-17 11:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0039_auto_20170109_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2017, 2, 17, 11, 43, 52, 852514, tzinfo=utc)),
        ),
    ]
