# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-17 12:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0040_auto_20170217_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2017, 2, 17, 12, 5, 39, 423947, tzinfo=utc)),
        ),
    ]
