# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-16 11:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0043_auto_20170301_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2017, 3, 16, 11, 46, 33, 783046, tzinfo=utc)),
        ),
    ]
