# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-18 20:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0045_auto_20170316_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2017, 3, 18, 20, 13, 25, 968979, tzinfo=utc)),
        ),
    ]
