# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-25 12:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0052_auto_20170324_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2017, 3, 25, 12, 19, 50, 232568, tzinfo=utc)),
        ),
    ]
