# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-27 17:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0055_auto_20170325_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2017, 3, 27, 17, 29, 39, 140929, tzinfo=utc)),
        ),
    ]
