# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-04 11:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0057_auto_20170404_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2017, 4, 4, 11, 37, 10, 664008, tzinfo=utc)),
        ),
    ]
