# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-05 09:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0058_auto_20170404_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2017, 4, 5, 9, 6, 59, 491956, tzinfo=utc)),
        ),
    ]
