# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-06 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0060_auto_20170405_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name=b'email address'),
        ),
    ]
