# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-08 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0064_remove_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='\u041a\u043e\u043d\u0442\u0435\u043d\u0442'),
        ),
    ]
