# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-26 13:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='realprice',
            new_name='oldprice',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='discountprice',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='economy',
        ),
        migrations.AlterField(
            model_name='comments',
            name='date_add',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 26, 15, 47, 3, 255197), verbose_name=b'\xd0\x94\xd0\xb0\xd1\x82\xd0\xb0 \xd0\xbf\xd1\x83\xd0\xb1\xd0\xbb\xd0\xb8\xd0\xba\xd0\xb0\xd1\x86\xd0\xb8\xd0\xb8'),
        ),
    ]
