# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-02 13:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20170102_1434'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdelivery',
            options={'verbose_name': '\u0422\u0438\u043f \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0438', 'verbose_name_plural': '\u0422\u0438\u043f \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0438'},
        ),
        migrations.AlterModelOptions(
            name='orderpayment',
            options={'verbose_name': '\u0422\u0438\u043f \u043e\u043f\u043b\u0430\u0442\u044b', 'verbose_name_plural': '\u0422\u0438\u043f \u043e\u043f\u043b\u0430\u0442\u044b '},
        ),
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'verbose_name': '\u0421\u0442\u0430\u0442\u0443\u0441 \u0437\u0430\u043a\u0430\u0437\u0430', 'verbose_name_plural': '\u0421\u0442\u0430\u0442\u0443\u0441 \u0437\u0430\u043a\u0430\u0437\u0430 '},
        ),
        migrations.AlterField(
            model_name='comments',
            name='date_add',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 2, 15, 57, 43, 414436), verbose_name=b'\xd0\x94\xd0\xb0\xd1\x82\xd0\xb0 \xd0\xbf\xd1\x83\xd0\xb1\xd0\xbb\xd0\xb8\xd0\xba\xd0\xb0\xd1\x86\xd0\xb8\xd0\xb8'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 1, 2, 15, 57, 43, 418155), verbose_name=b'\xd0\x94\xd0\xb0\xd1\x82\xd0\xb0 \xd0\xbf\xd1\x83\xd0\xb1\xd0\xbb\xd0\xb8\xd0\xba\xd0\xb0\xd1\x86\xd0\xb8\xd0\xb8'),
        ),
    ]
