# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-05 21:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20170105_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='send_mail',
            field=models.BooleanField(default=False, verbose_name=b'\xd0\x91\xd1\x8b\xd1\x81\xd1\x82\xd1\x80\xd1\x8b\xd0\xb9 \xd0\xb7\xd0\xb0\xd0\xba\xd0\xb0\xd0\xb7'),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='send_sms',
            field=models.BooleanField(default=False, verbose_name=b'\xd0\x91\xd1\x8b\xd1\x81\xd1\x82\xd1\x80\xd1\x8b\xd0\xb9 \xd0\xb7\xd0\xb0\xd0\xba\xd0\xb0\xd0\xb7'),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='text_mail',
            field=models.TextField(blank=True, default=b'', null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='text_sms',
            field=models.TextField(blank=True, default=b'', null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date_add',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 5, 23, 48, 32, 511895), verbose_name=b'\xd0\x94\xd0\xb0\xd1\x82\xd0\xb0 \xd0\xbf\xd1\x83\xd0\xb1\xd0\xbb\xd0\xb8\xd0\xba\xd0\xb0\xd1\x86\xd0\xb8\xd0\xb8'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 1, 5, 23, 48, 32, 518911), verbose_name=b'\xd0\x94\xd0\xb0\xd1\x82\xd0\xb0 \xd0\xbf\xd1\x83\xd0\xb1\xd0\xbb\xd0\xb8\xd0\xba\xd0\xb0\xd1\x86\xd0\xb8\xd0\xb8'),
        ),
    ]
