# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-05 21:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20170105_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date_add',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 5, 23, 53, 42, 821858), verbose_name=b'\xd0\x94\xd0\xb0\xd1\x82\xd0\xb0 \xd0\xbf\xd1\x83\xd0\xb1\xd0\xbb\xd0\xb8\xd0\xba\xd0\xb0\xd1\x86\xd0\xb8\xd0\xb8'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 1, 5, 23, 53, 42, 825946), verbose_name=b'\xd0\x94\xd0\xb0\xd1\x82\xd0\xb0 \xd0\xbf\xd1\x83\xd0\xb1\xd0\xbb\xd0\xb8\xd0\xba\xd0\xb0\xd1\x86\xd0\xb8\xd0\xb8'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='send_mail',
            field=models.BooleanField(default=False, verbose_name=b'\xd0\x9e\xd1\x82\xd0\xbf\xd1\x80\xd0\xb0\xd0\xb2\xd0\xbb\xd1\x8f\xd1\x82\xd1\x8c \xd0\xbc\xd0\xb5\xd0\xb9\xd0\xbb'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='send_sms',
            field=models.BooleanField(default=False, verbose_name=b'\xd0\x9e\xd1\x82\xd0\xbf\xd1\x80\xd0\xb0\xd0\xb2\xd0\xbb\xd1\x8f\xd1\x82\xd1\x8c \xd1\x81\xd0\xbc\xd1\x81'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='text_mail',
            field=models.TextField(blank=True, default=b'', null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043c\u0435\u0439\u043b\u0430'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='text_sms',
            field=models.TextField(blank=True, default=b'', null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0441\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u044f'),
        ),
    ]
