# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-08 14:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_auto_20170108_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nal',
            field=models.BooleanField(default=False, verbose_name=b'\xd0\x92 \xd0\xbd\xd0\xb0\xd0\xbb\xd0\xb8\xd1\x87\xd0\xb0\xd0\xb5'),
        ),
        migrations.AddField(
            model_name='product',
            name='search',
            field=models.TextField(blank=True, default=b'', null=True, verbose_name='\u041f\u043e\u0438\u0441\u043a'),
        ),
        migrations.AddField(
            model_name='product',
            name='search_text',
            field=models.TextField(blank=True, default=b'', null=True, verbose_name='\u041f\u043e\u0438\u0441\u043a \u0441\u043b\u0443\u0436\u0435\u0431\u043d\u044b\u0439'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date_add',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 8, 16, 57, 43, 990511), verbose_name=b'\xd0\x94\xd0\xb0\xd1\x82\xd0\xb0 \xd0\xbf\xd1\x83\xd0\xb1\xd0\xbb\xd0\xb8\xd0\xba\xd0\xb0\xd1\x86\xd0\xb8\xd0\xb8'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 1, 8, 16, 57, 44, 1188), verbose_name=b'\xd0\x94\xd0\xb0\xd1\x82\xd0\xb0 \xd0\xbf\xd1\x83\xd0\xb1\xd0\xbb\xd0\xb8\xd0\xba\xd0\xb0\xd1\x86\xd0\xb8\xd0\xb8'),
        ),
    ]
