# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-16 20:23
from __future__ import unicode_literals

import content.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import shop.models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0042_auto_20170316_2223'),
        ('shop', '0036_auto_20170301_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name=b'\xd0\x9d\xd0\xb0\xd0\xb7\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5')),
                ('image', content.fields.ThumbnailImageField(blank=True, upload_to=shop.models.make_upload_path, verbose_name=b'\xd0\x98\xd0\xb7\xd0\xbe\xd0\xb1\xd1\x80\xd0\xb0\xd0\xb6\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name=b'\xd0\x97\xd0\xb0\xd0\xb3\xd0\xbe\xd0\xbb\xd0\xbe\xd0\xb2\xd0\xbe\xd0\xba \xd0\xb2 \xd0\xb1\xd1\x80\xd0\xb0\xd1\x83\xd0\xb7\xd0\xb5\xd1\x80\xd0\xb5')),
                ('metaKey', models.CharField(blank=True, max_length=250, verbose_name=b'\xd0\x9a\xd0\xbb\xd1\x8e\xd1\x87\xd0\xb5\xd0\xb2\xd1\x8b\xd0\xb5 \xd1\x81\xd0\xbb\xd0\xbe\xd0\xb2\xd0\xb0')),
                ('metaDesc', models.CharField(blank=True, max_length=250, verbose_name=b'\xd0\x9e\xd0\xbf\xd0\xb8\xd1\x81\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5')),
                ('slug', models.CharField(blank=True, max_length=250, verbose_name=b'\xd0\xa3\xd1\x80\xd0\xbb')),
                ('short_text', tinymce.models.HTMLField(blank=True, verbose_name=b'\xd0\x9a\xd0\xbe\xd1\x80\xd0\xbe\xd1\x82\xd0\xba\xd0\xbe\xd0\xb5 \xd0\xbe\xd0\xbf\xd0\xb8\xd1\x81\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5')),
                ('full_text', tinymce.models.HTMLField(blank=True, verbose_name=b'\xd0\x9f\xd0\xbe\xd0\xbb\xd0\xbd\xd0\xbe\xd0\xb5 \xd0\xbe\xd0\xbf\xd0\xb8\xd1\x81\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5')),
                ('pub_date', models.DateField(blank=True, default=datetime.date(2017, 3, 16), verbose_name=b'\xd0\x94\xd0\xb0\xd1\x82\xd0\xb0 \xd0\xbf\xd1\x83\xd0\xb1\xd0\xbb\xd0\xb8\xd0\xba\xd0\xb0\xd1\x86\xd0\xb8\xd0\xb8')),
                ('published', models.BooleanField(default=False, verbose_name=b'\xd0\x9e\xd0\xbf\xd1\x83\xd0\xb1\xd0\xbb\xd0\xb8\xd0\xba\xd0\xbe\xd0\xb2\xd0\xb0\xd0\xbd')),
                ('ordering', models.IntegerField(blank=True, default=0, null=True, verbose_name=b'\xd0\x9f\xd0\xbe\xd1\x80\xd1\x8f\xd0\xb4\xd0\xbe\xd0\xba \xd1\x81\xd0\xbe\xd1\x80\xd1\x82\xd0\xb8\xd1\x80\xd0\xbe\xd0\xb2\xd0\xba\xd0\xb8')),
            ],
            options={
                'verbose_name_plural': '\u0421\u0442\u0430\u0442\u044c\u0438',
            },
        ),
        migrations.CreateModel(
            name='BrandDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name=b'\xd0\x97\xd0\xb0\xd0\xb3\xd0\xbe\xd0\xbb\xd0\xbe\xd0\xb2\xd0\xbe\xd0\xba \xd0\xb2 \xd0\xb1\xd1\x80\xd0\xb0\xd1\x83\xd0\xb7\xd0\xb5\xd1\x80\xd0\xb5')),
                ('metaKey', models.CharField(blank=True, max_length=250, verbose_name=b'\xd0\x9a\xd0\xbb\xd1\x8e\xd1\x87\xd0\xb5\xd0\xb2\xd1\x8b\xd0\xb5 \xd1\x81\xd0\xbb\xd0\xbe\xd0\xb2\xd0\xb0')),
                ('metaDesc', models.CharField(blank=True, max_length=250, verbose_name=b'\xd0\x9c\xd0\xb5\xd1\x82\xd0\xb0 \xd0\xbe\xd0\xbf\xd0\xb8\xd1\x81\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5')),
                ('full_text', tinymce.models.HTMLField(blank=True, verbose_name=b'\xd0\x9e\xd0\xbf\xd0\xb8\xd1\x81\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5 \xd0\xb1\xd1\x80\xd0\xb5\xd0\xbd\xd0\xb4\xd0\xb0')),
            ],
            options={
                'verbose_name': 'Seo \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0434\u043b\u044f \u0431\u0440\u0435\u043d\u0434\u0430',
                'verbose_name_plural': 'Seo \u041e\u043f\u0438\u0441\u0430\u043d\u0438\u044f \u0434\u043b\u044f \u0431\u0440\u0435\u043d\u0434\u043e\u0432',
            },
        ),
        migrations.CreateModel(
            name='CategorySinonim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name=b'\xd0\x9d\xd0\xb0\xd0\xb7\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5')),
            ],
            options={
                'verbose_name_plural': '\u0421\u0438\u043d\u043e\u043d\u0438\u043c \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438',
            },
        ),
        migrations.CreateModel(
            name='ColorProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'0', max_length=250, null=True, verbose_name='\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435')),
                ('main', models.BooleanField(default=False, verbose_name=b'Main color')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name=b'\xd0\xa6\xd0\xb5\xd0\xbd\xd0\xb0')),
                ('price_in', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name=b'\xd0\xa6\xd0\xb5\xd0\xbd\xd0\xb0 \xd0\x92\xd1\x85\xd0\xbe\xd0\xb4\xd0\xb0')),
                ('oldprice', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name=b'\xd0\xa1\xd1\x82\xd0\xb0\xd1\x80\xd0\xb0\xd1\x8f \xd1\x86\xd0\xb5\xd0\xbd\xd0\xb0')),
                ('image1', content.fields.ThumbnailImageField(blank=True, upload_to=shop.models.make_upload_path, verbose_name=b'\xd0\x98\xd0\xb7\xd0\xbe\xd0\xb1\xd1\x80\xd0\xb0\xd0\xb6\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5 1')),
                ('image2', content.fields.ThumbnailImageField(blank=True, upload_to=shop.models.make_upload_path, verbose_name=b'\xd0\x98\xd0\xb7\xd0\xbe\xd0\xb1\xd1\x80\xd0\xb0\xd0\xb6\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5 2')),
                ('image3', content.fields.ThumbnailImageField(blank=True, upload_to=shop.models.make_upload_path, verbose_name=b'\xd0\x98\xd0\xb7\xd0\xbe\xd0\xb1\xd1\x80\xd0\xb0\xd0\xb6\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5 3')),
                ('image4', content.fields.ThumbnailImageField(blank=True, upload_to=shop.models.make_upload_path, verbose_name=b'\xd0\x98\xd0\xb7\xd0\xbe\xd0\xb1\xd1\x80\xd0\xb0\xd0\xb6\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5 4')),
                ('image5', content.fields.ThumbnailImageField(blank=True, upload_to=shop.models.make_upload_path, verbose_name=b'\xd0\x98\xd0\xb7\xd0\xbe\xd0\xb1\xd1\x80\xd0\xb0\xd0\xb6\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5 5')),
                ('idname', models.CharField(max_length=250, verbose_name=b'\xd0\x9a\xd0\xbe\xd0\xb4 \xd0\xb4\xd0\xbb\xd1\x8f 1\xd0\xa1')),
                ('ordering', models.IntegerField(blank=True, default=0, null=True, verbose_name=b'\xd0\x9f\xd0\xbe\xd1\x80\xd1\x8f\xd0\xb4\xd0\xbe\xd0\xba \xd1\x81\xd0\xbe\xd1\x80\xd1\x82\xd0\xb8\xd1\x80\xd0\xbe\xd0\xb2\xd0\xba\xd0\xb8')),
                ('href', models.CharField(blank=True, max_length=250, verbose_name=b'Hotline url')),
                ('hrefok', models.BooleanField(default=False, verbose_name=b'Hotline url OK')),
            ],
        ),
        migrations.CreateModel(
            name='ColorRGB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u0418\u043c\u044f')),
                ('rgb', models.CharField(default=b'#fff', max_length=50, verbose_name='RGB')),
            ],
        ),
        migrations.CreateModel(
            name='Complect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name_plural': '\u0410\u043a\u0446\u0438\u043e\u043d\u043d\u044b\u0439 \u043a\u043e\u043c\u043f\u043b\u0435\u043a\u0442',
            },
        ),
        migrations.CreateModel(
            name='ComplectItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField(default=0, verbose_name='\u041f\u0440\u043e\u0446\u0435\u043d\u0442')),
                ('order', models.IntegerField(default=0, verbose_name='\u041f\u043e\u0440\u044f\u0434\u043e\u043a')),
                ('complect', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='color_complect', to='shop.Complect', verbose_name='\u0424\u0438\u043b\u044c\u0442\u0440')),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='color_complectitem', to='shop.ColorProduct', verbose_name='\u041f\u0440\u043e\u0434\u0443\u043a\u0442')),
            ],
            options={
                'verbose_name_plural': '\u041e\u0434\u0438\u043d \u043a\u043e\u043c\u043f\u043b\u0435\u043a\u0442',
            },
        ),
        migrations.CreateModel(
            name='Ecomerce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=250, verbose_name='Url')),
                ('name', models.CharField(blank=True, max_length=250, verbose_name='Name')),
                ('keywords', models.TextField(default=b'', verbose_name='Kewords')),
                ('is_index', models.BooleanField(default=False, verbose_name=b'\xd0\x92 \xd0\xb8\xd0\xbd\xd0\xb4\xd0\xb5\xd0\xba\xd1\x81\xd0\xb5')),
                ('newnode', models.BooleanField(default=True, verbose_name=b'\xd0\x9d\xd0\xbe\xd0\xb2\xd0\xbe\xd0\xb5')),
                ('pub_date', models.DateTimeField(blank=True, default=datetime.datetime(2017, 3, 16, 22, 23, 15, 867881), verbose_name=b'\xd0\x94\xd0\xb0\xd1\x82\xd0\xb0 \xd0\xbf\xd1\x83\xd0\xb1\xd0\xbb\xd0\xb8\xd0\xba\xd0\xb0\xd1\x86\xd0\xb8\xd0\xb8')),
                ('type', models.IntegerField(choices=[(1, b'category'), (2, b'category brand'), (3, b'category filter'), (4, b'product'), (5, b'product color'), (6, b'folder')], default=0, verbose_name='TYPE')),
                ('source_id', models.IntegerField(default=0, verbose_name=b'Source id')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.Ecomerce', verbose_name='\u0420\u043e\u0434\u0438\u0442\u0435\u043b\u044c\u0441\u043a\u0438\u0439 \u043f\u0443\u043d\u043a\u0442 \u043c\u0435\u043d\u044e')),
            ],
            options={
                'verbose_name': 'Ecomerce',
                'verbose_name_plural': 'Ecomerce',
            },
        ),
        migrations.CreateModel(
            name='EcomerceCaptcha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.IntegerField(default=0, verbose_name='Request')),
                ('hiddenid', models.CharField(blank=True, max_length=250, null=True, verbose_name='Hiddenid')),
                ('response', models.CharField(blank=True, max_length=250, null=True, verbose_name='Response')),
            ],
        ),
        migrations.CreateModel(
            name='EcomercePhrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, verbose_name='Name')),
                ('frequency_google', models.IntegerField(default=0, verbose_name='Frequency Adwords')),
                ('frequency_yandex', models.IntegerField(default=0, verbose_name='Frequency Yandex')),
                ('nowposition_google', models.IntegerField(default=0, verbose_name='Nowposition Google')),
                ('nowposition_yandex', models.IntegerField(default=0, verbose_name='Nowposition Yandex')),
                ('lastposition_google', models.IntegerField(default=0, verbose_name='Lastposition Google')),
                ('lastposition_yandex', models.IntegerField(default=0, verbose_name='Lastposition Yandex')),
                ('nofound', models.BooleanField(default=False, verbose_name=b'\xd0\x9d\xd0\xb5 \xd0\xbd\xd0\xb0\xd0\xb9\xd0\xb4\xd0\xb5\xd0\xbd\xd0\xbe')),
                ('active', models.BooleanField(default=True, verbose_name=b'active')),
                ('url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Ecomerce', verbose_name=b'Url')),
            ],
        ),
        migrations.CreateModel(
            name='EcomercePosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0, verbose_name='position')),
                ('pub_date', models.DateTimeField(blank=True, default=datetime.datetime(2017, 3, 16, 22, 23, 15, 869922), verbose_name=b'\xd0\x94\xd0\xb0\xd1\x82\xd0\xb0 \xd0\xbf\xd1\x83\xd0\xb1\xd0\xbb\xd0\xb8\xd0\xba\xd0\xb0\xd1\x86\xd0\xb8\xd0\xb8')),
                ('url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.EcomercePhrase', verbose_name=b'phrase')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=True, default=0, null=True, verbose_name=b'\xd0\x9a\xd0\xbe\xd0\xbb\xd0\xb8\xd1\x87\xd0\xb5\xd1\x81\xd1\x82\xd0\xb2\xd0\xbe \xd1\x82\xd0\xbe\xd0\xb2\xd0\xb0\xd1\x80\xd0\xbe\xd0\xb2')),
            ],
        ),
        migrations.CreateModel(
            name='FilterSelect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=250, verbose_name=b'\xd0\x97\xd0\xbd\xd0\xb0\xd1\x87\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5')),
                ('ordering', models.IntegerField(blank=True, default=0, null=True, verbose_name=b'\xd0\x9f\xd0\xbe\xd1\x80\xd1\x8f\xd0\xb4\xd0\xbe\xd0\xba \xd1\x81\xd0\xbe\xd1\x80\xd1\x82\xd0\xb8\xd1\x80\xd0\xbe\xd0\xb2\xd0\xba\xd0\xb8')),
                ('slug', models.CharField(blank=True, db_index=True, default=b'', max_length=250, verbose_name=b'\xd0\xa3\xd1\x80\xd0\xbb')),
            ],
            options={
                'verbose_name': '\u0424\u0438\u043b\u044c\u0442\u0440\u044b \u0432\u044b\u0431\u043e\u0440\u043e\u0432',
                'verbose_name_plural': '\u0424\u0438\u043b\u044c\u0442\u0440 \u0432\u044b\u0431\u043e\u0440\u0430',
            },
        ),
        migrations.CreateModel(
            name='FilterSeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1', models.CharField(max_length=250, verbose_name=b'\xd0\x9d\xd0\xb0\xd0\xb7\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name=b'\xd0\x97\xd0\xb0\xd0\xb3\xd0\xbe\xd0\xbb\xd0\xbe\xd0\xb2\xd0\xbe\xd0\xba \xd0\xb2 \xd0\xb1\xd1\x80\xd0\xb0\xd1\x83\xd0\xb7\xd0\xb5\xd1\x80\xd0\xb5')),
                ('metaKey', models.CharField(blank=True, max_length=250, verbose_name=b'\xd0\x9a\xd0\xbb\xd1\x8e\xd1\x87\xd0\xb5\xd0\xb2\xd1\x8b\xd0\xb5 \xd1\x81\xd0\xbb\xd0\xbe\xd0\xb2\xd0\xb0')),
                ('metaDesc', models.CharField(blank=True, max_length=250, verbose_name=b'\xd0\x9e\xd0\xbf\xd0\xb8\xd1\x81\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5')),
                ('text', tinymce.models.HTMLField(blank=True, verbose_name=b'\xd0\x9a\xd0\xbe\xd1\x80\xd0\xbe\xd1\x82\xd0\xba\xd0\xbe\xd0\xb5 \xd0\xbe\xd0\xbf\xd0\xb8\xd1\x81\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5')),
                ('slug', models.CharField(blank=True, max_length=250, verbose_name=b'\xd0\xa3\xd1\x80\xd0\xbb')),
                ('active', models.BooleanField(default=True, verbose_name=b'\xd0\x9e\xd0\xbf\xd1\x83\xd0\xb1\xd0\xbb\xd0\xb8\xd0\xba\xd0\xbe\xd0\xb2\xd0\xb0\xd0\xbd')),
            ],
            options={
                'verbose_name': '\u0444\u0438\u043b\u044c\u0442\u0440\u044b \u0434\u043b\u044f \u0441\u0435\u043e',
            },
        ),
        migrations.CreateModel(
            name='LowPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name=b'\xd0\x97\xd0\xb0\xd0\xb3\xd0\xbe\xd0\xbb\xd0\xbe\xd0\xb2\xd0\xbe\xd0\xba \xd0\xb2 \xd0\xb1\xd1\x80\xd0\xb0\xd1\x83\xd0\xb7\xd0\xb5\xd1\x80\xd0\xb5')),
                ('metaKey', models.CharField(blank=True, max_length=250, verbose_name=b'\xd0\x9a\xd0\xbb\xd1\x8e\xd1\x87\xd0\xb5\xd0\xb2\xd1\x8b\xd0\xb5 \xd1\x81\xd0\xbb\xd0\xbe\xd0\xb2\xd0\xb0')),
                ('metaDesc', models.CharField(blank=True, max_length=250, verbose_name=b'\xd0\x9e\xd0\xbf\xd0\xb8\xd1\x81\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5')),
                ('full_text', tinymce.models.HTMLField(blank=True, verbose_name=b'\xd0\x9a\xd0\xbe\xd1\x80\xd0\xbe\xd1\x82\xd0\xba\xd0\xbe\xd0\xb5 \xd0\xbe\xd0\xbf\xd0\xb8\xd1\x81\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5')),
            ],
            options={
                'verbose_name': 'Seo \u043d\u0435\u0434\u043e\u0440\u043e\u0433\u043e',
                'verbose_name_plural': 'Seo \u041d\u0435\u0434\u043e\u0440\u043e\u0433\u043e',
            },
        ),
        migrations.CreateModel(
            name='OrderColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='\u0426\u0435\u043d\u0430')),
                ('count', models.IntegerField(default=0, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ColorProduct', verbose_name='\u0426\u0432\u0435\u0442 \u0442\u043e\u0432\u0430\u0440\u0430')),
            ],
        ),
        migrations.CreateModel(
            name='OrderComplect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='\u0426\u0435\u043d\u0430')),
                ('count', models.IntegerField(default=0, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e')),
                ('complect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Complect', verbose_name='\u041a\u043e\u043c\u043f\u043b\u0435\u043a\u0442')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=255, verbose_name='\u0410\u0434\u0440\u0435\u0441\u0441 \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0438')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('image', content.fields.ThumbnailImageField(blank=True, upload_to=shop.models.make_upload_path, verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435')),
            ],
        ),
        migrations.CreateModel(
            name='Popular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name=b'\xd0\x97\xd0\xb0\xd0\xb3\xd0\xbe\xd0\xbb\xd0\xbe\xd0\xb2\xd0\xbe\xd0\xba \xd0\xb2 \xd0\xb1\xd1\x80\xd0\xb0\xd1\x83\xd0\xb7\xd0\xb5\xd1\x80\xd0\xb5')),
                ('metaKey', models.CharField(blank=True, max_length=250, verbose_name=b'\xd0\x9a\xd0\xbb\xd1\x8e\xd1\x87\xd0\xb5\xd0\xb2\xd1\x8b\xd0\xb5 \xd1\x81\xd0\xbb\xd0\xbe\xd0\xb2\xd0\xb0')),
                ('metaDesc', models.CharField(blank=True, max_length=250, verbose_name=b'\xd0\x9e\xd0\xbf\xd0\xb8\xd1\x81\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5')),
                ('full_text', tinymce.models.HTMLField(blank=True, verbose_name=b'\xd0\x9a\xd0\xbe\xd1\x80\xd0\xbe\xd1\x82\xd0\xba\xd0\xbe\xd0\xb5 \xd0\xbe\xd0\xbf\xd0\xb8\xd1\x81\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5')),
            ],
            options={
                'verbose_name': 'Seo \u043f\u043e\u043f\u0443\u043b\u044f\u0440\u043d\u044b\u0435',
                'verbose_name_plural': 'Seo \u041f\u043e\u043f\u0443\u043b\u044f\u0440\u043d\u044b\u0435',
            },
        ),
        migrations.CreateModel(
            name='ProductViews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=datetime.date(2017, 3, 16), verbose_name=b'\xd0\x94\xd0\xb0\xd1\x82\xd0\xb0 \xd0\xbf\xd1\x83\xd0\xb1\xd0\xbb\xd0\xb8\xd0\xba\xd0\xb0\xd1\x86\xd0\xb8\xd0\xb8')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('ordering', models.IntegerField(blank=True, default=0, null=True, verbose_name=b'\xd0\x9f\xd0\xbe\xd1\x80\xd1\x8f\xd0\xb4\xd0\xbe\xd0\xba \xd1\x81\xd0\xbe\xd1\x80\xd1\x82\xd0\xb8\xd1\x80\xd0\xbe\xd0\xb2\xd0\xba\xd0\xb8')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=250, verbose_name='\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435')),
            ],
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, verbose_name='Name')),
                ('active', models.BooleanField(default=True, verbose_name=b'active')),
            ],
            options={
                'verbose_name': 'Proxy',
                'verbose_name_plural': 'Proxy',
            },
        ),
        migrations.CreateModel(
            name='ProxyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.TextField(verbose_name=b'List of proxy')),
            ],
            options={
                'verbose_name': 'ProxyList',
                'verbose_name_plural': 'ProxyList',
            },
        ),
        migrations.CreateModel(
            name='QuikOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=250, verbose_name=b'\xd0\xa2\xd0\xb5\xd0\xbb\xd0\xb5\xd1\x84\xd0\xbe\xd0\xbd')),
                ('proccessed', models.BooleanField(default=False, verbose_name=b'\xd0\x9e\xd0\xb1\xd1\x80\xd0\xb0\xd0\xb1\xd0\xbe\xd1\x82\xd0\xb0\xd0\xbd')),
                ('pub_date', models.DateTimeField(blank=True, default=datetime.datetime(2017, 3, 16, 22, 23, 15, 861397), verbose_name=b'\xd0\x94\xd0\xb0\xd1\x82\xd0\xb0 \xd0\xbf\xd1\x83\xd0\xb1\xd0\xbb\xd0\xb8\xd0\xba\xd0\xb0\xd1\x86\xd0\xb8\xd0\xb8')),
            ],
            options={
                'verbose_name_plural': '\u0411\u044b\u0441\u0442\u0440\u044b\u0439 \u0437\u0430\u043a\u0430\u0437',
            },
        ),
        migrations.CreateModel(
            name='Seo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name=b'\xd0\x97\xd0\xb0\xd0\xb3\xd0\xbe\xd0\xbb\xd0\xbe\xd0\xb2\xd0\xbe\xd0\xba \xd0\xb2 \xd0\xb1\xd1\x80\xd0\xb0\xd1\x83\xd0\xb7\xd0\xb5\xd1\x80\xd0\xb5')),
                ('metaKey', models.CharField(blank=True, max_length=250, verbose_name=b'\xd0\x9a\xd0\xbb\xd1\x8e\xd1\x87\xd0\xb5\xd0\xb2\xd1\x8b\xd0\xb5 \xd1\x81\xd0\xbb\xd0\xbe\xd0\xb2\xd0\xb0')),
                ('metaDesc', models.CharField(blank=True, max_length=250, verbose_name=b'\xd0\x9e\xd0\xbf\xd0\xb8\xd1\x81\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5')),
                ('full_text', tinymce.models.HTMLField(blank=True, verbose_name=b'\xd0\x9a\xd0\xbe\xd1\x80\xd0\xbe\xd1\x82\xd0\xba\xd0\xbe\xd0\xb5 \xd0\xbe\xd0\xbf\xd0\xb8\xd1\x81\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5')),
            ],
            options={
                'verbose_name': 'Seo \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0430',
                'verbose_name_plural': 'Seo \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b',
            },
        ),
        migrations.CreateModel(
            name='SeoBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name=b'\xd0\x97\xd0\xb0\xd0\xb3\xd0\xbe\xd0\xbb\xd0\xbe\xd0\xb2\xd0\xbe\xd0\xba \xd0\xb2 \xd0\xb1\xd1\x80\xd0\xb0\xd1\x83\xd0\xb7\xd0\xb5\xd1\x80\xd0\xb5')),
                ('metaKey', models.CharField(blank=True, max_length=250, verbose_name=b'\xd0\x9a\xd0\xbb\xd1\x8e\xd1\x87\xd0\xb5\xd0\xb2\xd1\x8b\xd0\xb5 \xd1\x81\xd0\xbb\xd0\xbe\xd0\xb2\xd0\xb0')),
                ('metaDesc', models.CharField(blank=True, max_length=250, verbose_name=b'\xd0\x9e\xd0\xbf\xd0\xb8\xd1\x81\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5')),
                ('full_text', tinymce.models.HTMLField(blank=True, verbose_name=b'\xd0\x9a\xd0\xbe\xd1\x80\xd0\xbe\xd1\x82\xd0\xba\xd0\xbe\xd0\xb5 \xd0\xbe\xd0\xbf\xd0\xb8\xd1\x81\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5')),
            ],
            options={
                'verbose_name': 'Seo \u0431\u0440\u0435\u043d\u0434\u044b',
                'verbose_name_plural': 'Seo \u0411\u0440\u0435\u043d\u0434\u044b',
            },
        ),
        migrations.CreateModel(
            name='Statistica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=250, verbose_name='Session')),
                ('pub_date', models.DateTimeField(blank=True, default=datetime.datetime(2017, 3, 16, 22, 23, 15, 866782), verbose_name=b'\xd0\x94\xd0\xb0\xd1\x82\xd0\xb0 \xd0\xbf\xd1\x83\xd0\xb1\xd0\xbb\xd0\xb8\xd0\xba\xd0\xb0\xd1\x86\xd0\xb8\xd0\xb8')),
                ('source', models.CharField(blank=True, max_length=250, verbose_name='Source')),
                ('keywords', models.CharField(blank=True, max_length=250, verbose_name='Keywords')),
                ('startpage', models.CharField(blank=True, max_length=250, verbose_name='Startpage')),
                ('text', models.TextField(default=b'', verbose_name='\u0413\u0434\u0435 \u0445\u043e\u0434\u0438\u043b')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ColorProduct', verbose_name='\u0426\u0432\u0435\u0442\u0430')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u042e\u0437\u0435\u0440')),
            ],
            options={
                'verbose_name': '\u0421\u0442\u0430\u0442\u0438\u0441\u0442\u0438\u043a\u0430',
                'verbose_name_plural': '\u0421\u0442\u0430\u0442\u0438\u0441\u0442\u0438\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='Ucat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name=b'\xd0\x9d\xd0\xb0\xd0\xb7\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5')),
                ('old_id', models.IntegerField(blank=True, default=0, null=True, verbose_name=b'old_id')),
                ('allfilters', models.TextField(blank=True, null=True, verbose_name='\u0424\u0438\u043b\u044c\u0442\u0440\u044b')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.Ucat', verbose_name='\u0420\u043e\u0434\u0438\u0442\u0435\u043b\u044c\u0441\u043a\u0430\u044f \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f')),
            ],
            options={
                'verbose_name': '\u042e\u0433 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438',
                'verbose_name_plural': '\u042e\u0433 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438',
            },
        ),
        migrations.CreateModel(
            name='Uproduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name=b'\xd0\x9d\xd0\xb0\xd0\xb7\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5')),
                ('myname', models.CharField(max_length=250, verbose_name=b'\xd0\xbc\xd0\xbe\xd0\xb5 \xd0\xbd\xd0\xb0\xd0\xb7\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5')),
                ('name_rus', models.CharField(max_length=250, verbose_name=b'\xd0\x9d\xd0\xb0\xd0\xb7\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5 \xd1\x80\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xbe\xd0\xb5')),
                ('name_ukr', models.CharField(max_length=250, verbose_name=b'\xd0\x9d\xd0\xb0\xd0\xb7\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5 \xd1\x83\xd0\xba\xd1\x80\xd0\xb0\xd0\xb8\xd0\xbd\xd1\x81\xd0\xba\xd0\xbe\xd0\xb5')),
                ('articul', models.CharField(max_length=250, verbose_name=b'\xd0\x90\xd1\x80\xd1\x82\xd0\xb8\xd0\xba\xd1\x83\xd0\xbb')),
                ('barcode', models.CharField(max_length=250, verbose_name=b'\xd0\x91\xd0\xb0\xd1\x80\xd0\xba\xd0\xbe\xd0\xb4')),
                ('brand', models.CharField(max_length=250, verbose_name=b'\xd0\x91\xd1\x80\xd0\xb0\xd0\xbd\xd0\xb4')),
                ('descr', models.TextField(blank=True, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('guarant', models.CharField(blank=True, max_length=250, null=True, verbose_name='\u0413\u0430\u0440\u0430\u043d\u0442\u0438]')),
                ('old_id', models.IntegerField(blank=True, default=0, max_length=250, null=True, verbose_name=b'old_id')),
                ('photo', models.CharField(blank=True, max_length=250, null=True, verbose_name='\u0424\u043e\u0442\u043e')),
                ('url', models.CharField(blank=True, max_length=250, null=True, verbose_name='\u042e\u0440\u043b')),
                ('image', content.fields.ThumbnailImageField(blank=True, upload_to=shop.models.make_upload_path, verbose_name=b'\xd0\x98\xd0\xb7\xd0\xbe\xd0\xb1\xd1\x80\xd0\xb0\xd0\xb6\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5')),
                ('rprice_uah', models.IntegerField(blank=True, default=0, null=True, verbose_name=b'\xd0\xa0\xd0\xbe\xd0\xb7\xd0\xbd\xd0\xb8\xd1\x87\xd0\xbd\xd0\xb0\xd1\x8f \xd1\x86\xd0\xb5\xd0\xbd\xd0\xb0')),
                ('filters', models.TextField(blank=True, null=True, verbose_name='\u0424\u0438\u043b\u044c\u0442\u0440\u044b')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Ucat', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f')),
            ],
            options={
                'verbose_name': '\u042e\u0433 \u043f\u0440\u043e\u0434\u0443\u043a\u0442',
                'verbose_name_plural': '\u042e\u0433 \u043f\u0440\u043e\u0434\u0443\u043a\u0442',
            },
        ),
        migrations.RemoveField(
            model_name='comments',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productphoto',
            name='product',
        ),
        migrations.DeleteModel(
            name='SearchWords',
        ),
        migrations.DeleteModel(
            name='Subscribe',
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name_plural': '\u0411\u0440\u0435\u043d\u0434'},
        ),
        migrations.AlterModelOptions(
            name='filter',
            options={'verbose_name': '\u0424\u0438\u043b\u044c\u0442\u0440\u044b \u0434\u043b\u044f \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0439', 'verbose_name_plural': '\u0424\u0438\u043b\u044c\u0442\u0440 \u0434\u043b\u044f \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438'},
        ),
        migrations.AlterModelOptions(
            name='filteritem',
            options={'verbose_name_plural': '\u041e\u0434\u0438\u043d \u0424\u0438\u043b\u044c\u0442\u0440'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AlterModelOptions(
            name='orderdelivery',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name_plural': '\u041f\u0440\u043e\u0434\u0443\u043a\u0442'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='order',
            new_name='ordering',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='metadesc',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='text',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='top',
        ),
        migrations.RemoveField(
            model_name='category',
            name='color',
        ),
        migrations.RemoveField(
            model_name='category',
            name='top',
        ),
        migrations.RemoveField(
            model_name='filter',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='filter',
            name='top',
        ),
        migrations.RemoveField(
            model_name='filteritem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='filteritem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='filteritem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quikorder',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ttn',
        ),
        migrations.RemoveField(
            model_name='orderdelivery',
            name='name',
        ),
        migrations.RemoveField(
            model_name='orderdelivery',
            name='text',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='active',
        ),
        migrations.RemoveField(
            model_name='product',
            name='country',
        ),
        migrations.RemoveField(
            model_name='product',
            name='custom',
        ),
        migrations.RemoveField(
            model_name='product',
            name='customdays',
        ),
        migrations.RemoveField(
            model_name='product',
            name='filters',
        ),
        migrations.RemoveField(
            model_name='product',
            name='idcode',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material',
        ),
        migrations.RemoveField(
            model_name='product',
            name='metadesc',
        ),
        migrations.RemoveField(
            model_name='product',
            name='nal',
        ),
        migrations.RemoveField(
            model_name='product',
            name='search',
        ),
        migrations.RemoveField(
            model_name='product',
            name='search_text',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='text',
        ),
        migrations.RemoveField(
            model_name='product',
            name='top',
        ),
        migrations.RemoveField(
            model_name='product',
            name='topimage',
        ),
        migrations.AddField(
            model_name='brand',
            name='description',
            field=tinymce.models.HTMLField(blank=True, verbose_name=b'\xd0\x9a\xd0\xbe\xd1\x80\xd0\xbe\xd1\x82\xd0\xba\xd0\xbe\xd0\xb5 \xd0\xbe\xd0\xbf\xd0\xb8\xd1\x81\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5'),
        ),
        migrations.AddField(
            model_name='brand',
            name='full_text',
            field=tinymce.models.HTMLField(blank=True, verbose_name=b'\xd0\x9f\xd0\xbe\xd0\xbb\xd0\xbd\xd0\xbe\xd0\xb5 \xd0\xbe\xd0\xbf\xd0\xb8\xd1\x81\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5'),
        ),
        migrations.AddField(
            model_name='brand',
            name='metaDesc',
            field=models.CharField(blank=True, max_length=250, verbose_name=b'\xd0\x9e\xd0\xbf\xd0\xb8\xd1\x81\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5'),
        ),
        migrations.AddField(
            model_name='brand',
            name='metaKey',
            field=models.CharField(blank=True, max_length=250, verbose_name=b'\xd0\x9a\xd0\xbb\xd1\x8e\xd1\x87\xd0\xb5\xd0\xb2\xd1\x8b\xd0\xb5 \xd1\x81\xd0\xbb\xd0\xbe\xd0\xb2\xd0\xb0'),
        ),
        migrations.AddField(
            model_name='brand',
            name='ordering',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=b'\xd0\x9f\xd0\xbe\xd1\x80\xd1\x8f\xd0\xb4\xd0\xbe\xd0\xba \xd1\x81\xd0\xbe\xd1\x80\xd1\x82\xd0\xb8\xd1\x80\xd0\xbe\xd0\xb2\xd0\xba\xd0\xb8'),
        ),
        migrations.AddField(
            model_name='brand',
            name='pub_date',
            field=models.DateField(blank=True, default=datetime.date(2017, 3, 16), verbose_name=b'\xd0\x94\xd0\xb0\xd1\x82\xd0\xb0 \xd0\xbf\xd1\x83\xd0\xb1\xd0\xbb\xd0\xb8\xd0\xba\xd0\xb0\xd1\x86\xd0\xb8\xd0\xb8'),
        ),
        migrations.AddField(
            model_name='brand',
            name='published',
            field=models.BooleanField(default=False, verbose_name=b'\xd0\x9e\xd0\xbf\xd1\x83\xd0\xb1\xd0\xbb\xd0\xb8\xd0\xba\xd0\xbe\xd0\xb2\xd0\xb0\xd0\xbd'),
        ),
        migrations.AddField(
            model_name='category',
            name='allcounts',
            field=models.TextField(blank=True, null=True, verbose_name='\u041f\u043e\u0434\u0441\u0447\u0435\u0442 \u0434\u0430\u043d\u043d\u044b\u0445'),
        ),
        migrations.AddField(
            model_name='category',
            name='column',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=b'\xd0\x9a\xd0\xbe\xd0\xbb\xd0\xbe\xd0\xbd\xd0\xba\xd0\xb0'),
        ),
        migrations.AddField(
            model_name='category',
            name='google_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name=b'\xd0\xa6\xd0\xb5\xd0\xbd\xd0\xb0 Google \xd0\xb2 \xd0\xb4\xd0\xb5\xd0\xbd\xd1\x8c'),
        ),
        migrations.AddField(
            model_name='category',
            name='google_published',
            field=models.BooleanField(default=False, verbose_name=b'Google Published'),
        ),
        migrations.AddField(
            model_name='category',
            name='hotline',
            field=models.BooleanField(default=True, verbose_name=b'Hotline'),
        ),
        migrations.AddField(
            model_name='category',
            name='imagemenu',
            field=content.fields.ThumbnailImageField(blank=True, upload_to=shop.models.make_upload_path, verbose_name=b'\xd0\x98\xd0\xb7\xd0\xbe\xd0\xb1\xd1\x80\xd0\xb0\xd0\xb6\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5 \xd0\xb4\xd0\xbb\xd1\x8f \xd0\xb3\xd0\xbb\xd0\xb0\xd0\xb2\xd0\xbd\xd0\xbe\xd0\xb3\xd0\xbe \xd0\xbc\xd0\xb5\xd0\xbd\xd1\x8e'),
        ),
        migrations.AddField(
            model_name='category',
            name='metakey',
            field=models.CharField(blank=True, max_length=250, verbose_name=b'\xd0\x9a\xd0\xbb\xd1\x8e\xd1\x87\xd0\xb5\xd0\xb2\xd1\x8b\xd0\xb5 \xd1\x81\xd0\xbb\xd0\xbe\xd0\xb2\xd0\xb0'),
        ),
        migrations.AddField(
            model_name='category',
            name='nadavi',
            field=models.BooleanField(default=True, verbose_name=b'Nadavi'),
        ),
        migrations.AddField(
            model_name='category',
            name='namebread',
            field=models.CharField(default=b'', max_length=250, verbose_name=b'\xd0\x9d\xd0\xb0\xd0\xb7\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5 \xd0\x91\xd1\x80\xd0\xb5\xd0\xb0\xd0\xb4\xd0\xba\xd1\x80\xd0\xb0\xd0\xbc\xd0\xbf\xd1\x81'),
        ),
        migrations.AddField(
            model_name='category',
            name='priceua',
            field=models.BooleanField(default=True, verbose_name=b'Priceua'),
        ),
        migrations.AddField(
            model_name='category',
            name='published',
            field=models.BooleanField(default=False, verbose_name=b'\xd0\x9e\xd0\xbf\xd1\x83\xd0\xb1\xd0\xbb\xd0\xb8\xd0\xba\xd0\xbe\xd0\xb2\xd0\xb0\xd0\xbd'),
        ),
        migrations.AddField(
            model_name='category',
            name='seofilters',
            field=models.TextField(blank=True, null=True, verbose_name='\u0421\u0435\u043e \u0444\u0438\u043b\u044c\u0442\u0440\u044b'),
        ),
        migrations.AddField(
            model_name='filter',
            name='filtertype',
            field=models.IntegerField(choices=[(3, '\u0412\u044b\u0431\u043e\u0440 \u0444\u0438\u043b\u044c\u0442\u0440\u0430'), (4, '\u0412\u044b\u0431\u043e\u0440 \u043d\u0435\u0441\u043a\u043e\u043b\u044c\u043a\u0438\u0445 \u0444\u0438\u043b\u044c\u0442\u0440\u043e\u0432')], default=1, verbose_name=b'\xd0\x9d\xd0\xb0\xd0\xb7\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5'),
        ),
        migrations.AddField(
            model_name='filter',
            name='ordering',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=b'\xd0\x9f\xd0\xbe\xd1\x80\xd1\x8f\xd0\xb4\xd0\xbe\xd0\xba \xd1\x81\xd0\xbe\xd1\x80\xd1\x82\xd0\xb8\xd1\x80\xd0\xbe\xd0\xb2\xd0\xba\xd0\xb8'),
        ),
        migrations.AddField(
            model_name='filter',
            name='requery',
            field=models.BooleanField(default=False, verbose_name=b'\xd0\x9e\xd0\xb1\xd1\x8f\xd0\xb7\xd0\xb0\xd1\x82\xd0\xb5\xd0\xbb\xd0\xb5\xd0\xbd'),
        ),
        migrations.AddField(
            model_name='filter',
            name='slug',
            field=models.CharField(blank=True, max_length=250, verbose_name=b'\xd0\xa3\xd1\x80\xd0\xbb'),
        ),
        migrations.AddField(
            model_name='filteritem',
            name='product',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='shop.Product', verbose_name='\u041f\u0440\u043e\u0434\u0443\u043a\u0442'),
        ),
        migrations.AddField(
            model_name='filteritem',
            name='value',
            field=models.CharField(default=b'0', max_length=250, verbose_name='\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='order',
            name='allproducts',
            field=models.TextField(default=b'', verbose_name='\u0412\u0441\u0435 \u043f\u0440\u043e\u0434\u0443\u043a\u0442\u044b'),
        ),
        migrations.AddField(
            model_name='order',
            name='countprice',
            field=models.IntegerField(default=0, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e'),
        ),
        migrations.AddField(
            model_name='order',
            name='proccessed',
            field=models.BooleanField(default=False, verbose_name=b'\xd0\x9e\xd0\xb1\xd1\x80\xd0\xb0\xd0\xb1\xd0\xbe\xd1\x82\xd0\xb0\xd0\xbd'),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(through='shop.OrderProduct', to='shop.Product', verbose_name='\u041f\u0440\u043e\u0434\u0443\u043a\u0442\u044b'),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='deliveryservice',
            field=models.CharField(default=0, max_length=255, verbose_name='\u0421\u043b\u0443\u0436\u0431\u0430 \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0438'),
        ),
        migrations.AddField(
            model_name='product',
            name='action_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name=b'\xd0\x9d\xd0\xb0\xd0\xb7\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5 \xd0\x90\xd0\xba\xd1\x86\xd0\xb8\xd0\xb8'),
        ),
        migrations.AddField(
            model_name='product',
            name='action_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Article', verbose_name=b'\xd0\xa1\xd1\x82\xd1\x80\xd0\xb0\xd0\xbd\xd0\xb8\xd1\x86\xd0\xb0 \xd0\x90\xd0\xba\xd1\x86\xd0\xb8\xd0\xb8'),
        ),
        migrations.AddField(
            model_name='product',
            name='action_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 3, 16, 22, 23, 15, 840478), null=True, verbose_name=b'\xd0\x94\xd0\xb0\xd1\x82\xd0\xb0 \xd0\xbe\xd0\xba\xd0\xb0\xd0\xbd\xd1\x87\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5 \xd0\xb0\xd0\xba\xd1\x86\xd0\xb8\xd0\xb8'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_set',
            field=models.BooleanField(default=False, verbose_name=b'\xd0\x93\xd0\xbb\xd0\xb0\xd0\xb2\xd0\xbd\xd1\x8b\xd0\xb9 \xd1\x86\xd0\xb2\xd0\xb5\xd1\x82 \xd1\x83\xd1\x81\xd1\x82\xd0\xb0\xd0\xbd\xd0\xbe\xd0\xb2\xd0\xbb\xd0\xb5\xd0\xbd \xd1\x81\xd0\xbb\xd1\x83\xd0\xb6\xd0\xb5\xd0\xb1\xd0\xbd\xd1\x8b\xd0\xb9'),
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.TextField(blank=True, null=True, verbose_name='\u0426\u0432\u0435\u0442\u0430 \u0441\u043b\u0443\u0436\u0435\u0431\u043d\u0430\u044f'),
        ),
        migrations.AddField(
            model_name='product',
            name='count_views',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u043e\u0432'),
        ),
        migrations.AddField(
            model_name='product',
            name='count_votes',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=b'\xd0\x9a\xd0\xbe\xd0\xbb\xd0\xb8\xd1\x87\xd0\xb5\xd1\x81\xd1\x82\xd0\xb2\xd0\xbe \xd0\xb3\xd0\xbe\xd0\xbb\xd0\xbe\xd1\x81\xd0\xbe\xd0\xb2'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(blank=True, verbose_name=b'\xd0\x9a\xd0\xbe\xd1\x80\xd0\xbe\xd1\x82\xd0\xba\xd0\xbe\xd0\xb5 \xd0\xbe\xd0\xbf\xd0\xb8\xd1\x81\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5'),
        ),
        migrations.AddField(
            model_name='product',
            name='dopcategory',
            field=models.ManyToManyField(blank=True, null=True, related_name='dopcategory', to='shop.Category', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438'),
        ),
        migrations.AddField(
            model_name='product',
            name='extraproduct',
            field=models.ManyToManyField(blank=True, null=True, related_name='extra', to='shop.Product', verbose_name='\u0414\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0435 \u043f\u0440\u043e\u0434\u0443\u043a\u0442\u044b'),
        ),
        migrations.AddField(
            model_name='product',
            name='full_text',
            field=tinymce.models.HTMLField(blank=True, verbose_name=b'\xd0\x9f\xd0\xbe\xd0\xbb\xd0\xbd\xd0\xbe\xd0\xb5 \xd0\xbe\xd0\xbf\xd0\xb8\xd1\x81\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5'),
        ),
        migrations.AddField(
            model_name='product',
            name='giftproduct',
            field=models.ManyToManyField(blank=True, null=True, related_name='gift', to='shop.Product', verbose_name='\u041f\u043e\u0434\u0430\u0440\u043a\u0438 \u043a \u043f\u0440\u043e\u0434\u0443\u043a\u0442\u0443'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_gift',
            field=models.BooleanField(default=False, verbose_name=b'\xd0\x95\xd1\x81\xd1\x82\xd1\x8c \xd0\xbf\xd0\xbe\xd0\xb4\xd0\xb0\xd1\x80\xd0\xbe\xd0\xba'),
        ),
        migrations.AddField(
            model_name='product',
            name='hotline',
            field=models.BooleanField(default=True, verbose_name=b'Hotline'),
        ),
        migrations.AddField(
            model_name='product',
            name='idname',
            field=models.CharField(default=0, max_length=250, verbose_name=b'\xd0\x9a\xd0\xbe\xd0\xb4 \xd0\xb4\xd0\xbb\xd1\x8f 1\xd0\xa1'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name=b'\xd0\x9d\xd0\xbe\xd0\xb2\xd1\x8b\xd0\xb9 \xd0\xbf\xd1\x80\xd0\xbe\xd0\xb4\xd1\x83\xd0\xba\xd1\x82'),
        ),
        migrations.AddField(
            model_name='product',
            name='maincolor',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name=b'\xd0\x93\xd0\xbb\xd0\xb0\xd0\xb2\xd0\xbd\xd1\x8b\xd0\xb9 \xd1\x86\xd0\xb2\xd0\xb5\xd1\x82 (\xd0\xb5\xd1\x81\xd0\xbb\xd0\xb8 \xd0\xbd\xd1\x83\xd0\xb6\xd0\xbd\xd0\xbe)'),
        ),
        migrations.AddField(
            model_name='product',
            name='maincolor_id',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name=b'\xd0\x93\xd0\xbb\xd0\xb0\xd0\xb2\xd0\xbd\xd1\x8b\xd0\xb9 \xd1\x86\xd0\xb2\xd0\xb5\xd1\x82 (id)'),
        ),
        migrations.AddField(
            model_name='product',
            name='max_reit',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=2, null=True, verbose_name=b'\xd0\x9c\xd0\xb0\xd0\xba\xd1\x81\xd0\xb8\xd0\xbc\xd0\xb0\xd0\xbb\xd1\x8c\xd0\xbd\xd0\xb0\xd1\x8f \xd0\xbe\xd1\x86\xd0\xb5\xd0\xbd\xd0\xba\xd0\xb0'),
        ),
        migrations.AddField(
            model_name='product',
            name='metaDesc',
            field=models.CharField(blank=True, max_length=250, verbose_name=b'\xd0\x9e\xd0\xbf\xd0\xb8\xd1\x81\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5'),
        ),
        migrations.AddField(
            model_name='product',
            name='metaKey',
            field=models.CharField(blank=True, max_length=250, verbose_name=b'\xd0\x9a\xd0\xbb\xd1\x8e\xd1\x87\xd0\xb5\xd0\xb2\xd1\x8b\xd0\xb5 \xd1\x81\xd0\xbb\xd0\xbe\xd0\xb2\xd0\xb0'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_reit',
            field=models.DecimalField(blank=True, decimal_places=1, default=5.0, max_digits=2, null=True, verbose_name=b'\xd0\x9c\xd0\xb8\xd0\xbd\xd0\xb8\xd0\xbc\xd0\xb0\xd0\xbb\xd1\x8c\xd0\xbd\xd0\xb0\xd1\x8f \xd0\xbe\xd1\x86\xd0\xb5\xd0\xbd\xd0\xba\xd0\xb0'),
        ),
        migrations.AddField(
            model_name='product',
            name='nadavi',
            field=models.BooleanField(default=True, verbose_name=b'Nadavi'),
        ),
        migrations.AddField(
            model_name='product',
            name='newproduct',
            field=models.BooleanField(default=False, verbose_name=b'\xd0\x9d\xd0\xbe\xd0\xb2\xd0\xb8\xd0\xbd\xd0\xba\xd0\xb0'),
        ),
        migrations.AddField(
            model_name='product',
            name='ordering',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=b'\xd0\x9f\xd0\xbe\xd1\x80\xd1\x8f\xd0\xb4\xd0\xbe\xd0\xba \xd1\x81\xd0\xbe\xd1\x80\xd1\x82\xd0\xb8\xd1\x80\xd0\xbe\xd0\xb2\xd0\xba\xd0\xb8'),
        ),
        migrations.AddField(
            model_name='product',
            name='priceua',
            field=models.BooleanField(default=True, verbose_name=b'Priceua'),
        ),
        migrations.AddField(
            model_name='product',
            name='pub_date',
            field=models.DateField(blank=True, default=datetime.date(2017, 3, 16), verbose_name=b'\xd0\x94\xd0\xb0\xd1\x82\xd0\xb0 \xd0\xbf\xd1\x83\xd0\xb1\xd0\xbb\xd0\xb8\xd0\xba\xd0\xb0\xd1\x86\xd0\xb8\xd0\xb8'),
        ),
        migrations.AddField(
            model_name='product',
            name='published',
            field=models.BooleanField(default=False, verbose_name=b'\xd0\x9e\xd0\xbf\xd1\x83\xd0\xb1\xd0\xbb\xd0\xb8\xd0\xba\xd0\xbe\xd0\xb2\xd0\xb0\xd0\xbd'),
        ),
        migrations.AddField(
            model_name='product',
            name='recomendproduct',
            field=models.ManyToManyField(blank=True, null=True, related_name='recomend', to='shop.Product', verbose_name='\u0420\u0435\u043a\u043e\u043c\u0435\u043d\u0434\u043e\u0432\u0430\u0435\u043d\u043d\u044b\u0435  \u043f\u0440\u043e\u0434\u0443\u043a\u0442\u044b'),
        ),
        migrations.AddField(
            model_name='product',
            name='top20',
            field=models.BooleanField(default=False, verbose_name=b'Top20'),
        ),
        migrations.AddField(
            model_name='product',
            name='waranty',
            field=models.CharField(choices=[('\u0411\u0435\u0437 \u0433\u0430\u0440\u0430\u043d\u0442\u0438\u0438', '\u0411\u0435\u0437 \u0433\u0430\u0440\u0430\u043d\u0442\u0438\u0438'), ('3 \u043c\u0435\u0441\u044f\u0446\u0430', '3 \u043c\u0435\u0441\u044f\u0446\u0430'), ('6 \u043c\u0435\u0441\u044f\u0446\u0435\u0432', '6 \u043c\u0435\u0441\u044f\u0446\u0435\u0432'), ('12 \u043c\u0435\u0441\u044f\u0446\u0435\u0432', '12 \u043c\u0435\u0441\u044f\u0446\u0435\u0432'), ('24 \u043c\u0435\u0441\u044f\u0446\u0430', '24 \u043c\u0435\u0441\u044f\u0446\u0430')], default=b'12 \xd0\xbc\xd0\xb5\xd1\x81\xd1\x8f\xd1\x86\xd0\xb5\xd0\xb2', max_length=250, verbose_name=b'\xd0\x93\xd0\xb0\xd1\x80\xd0\xb0\xd0\xbd\xd1\x82\xd0\xb8\xd1\x8f'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=b'\xd0\x92\xd0\xb5\xd1\x81 \xd0\xb8\xd1\x81\xd0\xbf\xd0\xbe\xd0\xbb\xd1\x8c\xd0\xb7\xd1\x83\xd0\xb5\xd1\x82\xd1\x81\xd1\x8f \xd0\xb2 \xd0\xbf\xd0\xbe\xd0\xb8\xd1\x81\xd0\xba\xd0\xb5'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=content.fields.ThumbnailImageField(blank=True, upload_to=shop.models.make_upload_path, verbose_name=b'\xd0\x98\xd0\xb7\xd0\xbe\xd0\xb1\xd1\x80\xd0\xb0\xd0\xb6\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5'),
        ),
        migrations.AlterField(
            model_name='category',
            name='filters',
            field=models.ManyToManyField(blank=True, null=True, to='shop.Filter', verbose_name='\u0424\u0438\u043b\u044c\u0442\u0440\u044b'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=content.fields.ThumbnailImageField(blank=True, upload_to=shop.models.make_upload_path, verbose_name=b'\xd0\x98\xd0\xb7\xd0\xbe\xd0\xb1\xd1\x80\xd0\xb0\xd0\xb6\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5'),
        ),
        migrations.AlterField(
            model_name='category',
            name='text',
            field=tinymce.models.HTMLField(blank=True, verbose_name=b'\xd0\x9f\xd0\xbe\xd0\xbb\xd0\xbd\xd0\xbe\xd0\xb5 \xd0\xbe\xd0\xbf\xd0\xb8\xd1\x81\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='name',
            field=models.CharField(max_length=250, verbose_name=b'\xd0\x9d\xd0\xb0\xd0\xb7\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5'),
        ),
        migrations.AlterField(
            model_name='filteritem',
            name='filter',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='shop.Filter', verbose_name='\u0424\u0438\u043b\u044c\u0442\u0440'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.IntegerField(choices=[(1, b'\xd0\xa1\xd0\xb0\xd0\xbc\xd0\xbe\xd0\xb2\xd1\x8b\xd0\xb2\xd0\xbe\xd0\xb7'), (2, b'\xd0\x9a\xd1\x83\xd1\x80\xd1\x8c\xd0\xb5\xd1\x80\xd0\xbe\xd0\xbc'), (3, b'\xd0\x9d\xd0\xbe\xd0\xb2\xd0\xb0\xd1\x8f \xd0\xbf\xd0\xbe\xd1\x87\xd1\x82\xd0\xb0')], default=1, verbose_name='\u0421\u043f\u043e\u0441\u043e\u0431\u044b \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.IntegerField(choices=[(1, b'\xd0\x9d\xd0\xb0\xd0\xbb\xd0\xb8\xd1\x87\xd0\xbd\xd1\x8b\xd0\xbc\xd0\xb8'), (2, b'\xd0\x9f\xd1\x80\xd0\xb8\xd0\xb2\xd0\xb0\xd1\x82 24')], default=1, verbose_name='\u0421\u043f\u043e\u0441\u043e\u0431 \u043e\u043f\u043b\u0430\u0442\u044b'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=250, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 3, 16, 22, 23, 15, 853466), verbose_name=b'\xd0\x94\xd0\xb0\xd1\x82\xd0\xb0 \xd0\xbf\xd1\x83\xd0\xb1\xd0\xbb\xd0\xb8\xd0\xba\xd0\xb0\xd1\x86\xd0\xb8\xd0\xb8'),
        ),
        migrations.AlterField(
            model_name='orderdelivery',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Order', verbose_name='\u0417\u0430\u043a\u0430\u0437'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Brand', verbose_name=b'\xd0\x91\xd1\x80\xd0\xb5\xd0\xbd\xd0\xb4'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Category', verbose_name=b'\xd0\x9a\xd0\xb0\xd1\x82\xd0\xb5\xd0\xb3\xd0\xbe\xd1\x80\xd0\xb8\xd1\x8f'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=content.fields.ThumbnailImageField(blank=True, upload_to=shop.models.make_upload_path, verbose_name=b'\xd0\x98\xd0\xb7\xd0\xbe\xd0\xb1\xd1\x80\xd0\xb0\xd0\xb6\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5'),
        ),
        migrations.AlterField(
            model_name='product',
            name='oldprice',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name=b'\xd0\xa1\xd1\x82\xd0\xb0\xd1\x80\xd0\xb0\xd1\x8f \xd1\x86\xd0\xb5\xd0\xbd\xd0\xb0'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name=b'\xd0\xa6\xd0\xb5\xd0\xbd\xd0\xb0'),
        ),
        migrations.AlterField(
            model_name='product',
            name='reit',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=2, null=True, verbose_name=b'\xd0\xa0\xd0\xb5\xd0\xb9\xd1\x82\xd0\xb8\xd0\xbd\xd0\xb3'),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='OrderPayment',
        ),
        migrations.DeleteModel(
            name='OrderStatus',
        ),
        migrations.DeleteModel(
            name='ProductPhoto',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.AddField(
            model_name='seobrand',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Brand', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f'),
        ),
        migrations.AddField(
            model_name='seobrand',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Category', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f'),
        ),
        migrations.AddField(
            model_name='seo',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Category', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f'),
        ),
        migrations.AddField(
            model_name='seo',
            name='fil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.FilterSelect', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f'),
        ),
        migrations.AddField(
            model_name='quikorder',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Product', verbose_name='\u041f\u0440\u043e\u0434\u0443\u043a\u0442'),
        ),
        migrations.AddField(
            model_name='propertyproduct',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Product', verbose_name='\u041f\u0440\u043e\u0434\u0443\u043a\u0442'),
        ),
        migrations.AddField(
            model_name='propertyproduct',
            name='property',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Property', verbose_name='\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='productviews',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Product', verbose_name='\u041f\u0440\u043e\u0434\u0443\u043a\u0442'),
        ),
        migrations.AddField(
            model_name='popular',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Category', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f'),
        ),
        migrations.AddField(
            model_name='photo',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='shop.Product', verbose_name='\u041f\u0440\u043e\u0434\u0443\u043a\u0442'),
        ),
        migrations.AddField(
            model_name='orderplace',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Order', verbose_name='\u0417\u0430\u043a\u0430\u0437'),
        ),
        migrations.AddField(
            model_name='ordercomplect',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Order', verbose_name='\u0417\u0430\u043a\u0430\u0437'),
        ),
        migrations.AddField(
            model_name='ordercolor',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Order', verbose_name='\u0417\u0430\u043a\u0430\u0437'),
        ),
        migrations.AddField(
            model_name='lowprice',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Category', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f'),
        ),
        migrations.AddField(
            model_name='filterseo',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Brand', verbose_name=b'\xd0\x91\xd1\x80\xd0\xb5\xd0\xbd\xd0\xb4'),
        ),
        migrations.AddField(
            model_name='filterseo',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Category', verbose_name=b'\xd0\x9a\xd0\xb0\xd1\x82\xd0\xb5\xd0\xb3\xd0\xbe\xd1\x80\xd0\xb8\xd1\x8f'),
        ),
        migrations.AddField(
            model_name='filterseo',
            name='fs1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fs1', to='shop.FilterSelect', verbose_name=b'FIlter Select 1'),
        ),
        migrations.AddField(
            model_name='filterseo',
            name='fs2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fs2', to='shop.FilterSelect', verbose_name=b'FIlter Select 2'),
        ),
        migrations.AddField(
            model_name='filterseo',
            name='fs3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fs3', to='shop.FilterSelect', verbose_name=b'FIlter Select 3'),
        ),
        migrations.AddField(
            model_name='filterselect',
            name='filter',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Filter', verbose_name=b'\xd0\xa4\xd0\xb8\xd0\xbb\xd1\x8c\xd1\x82\xd1\x80'),
        ),
        migrations.AddField(
            model_name='extracategory',
            name='categort_to',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Category', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f'),
        ),
        migrations.AddField(
            model_name='extracategory',
            name='product_from',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Product', verbose_name='\u041f\u0440\u043e\u0434\u0443\u043a\u0442'),
        ),
        migrations.AddField(
            model_name='colorproduct',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_colors', to='shop.Product', verbose_name='\u041f\u0440\u043e\u0434\u0443\u043a\u0442'),
        ),
        migrations.AddField(
            model_name='colorproduct',
            name='rgb',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='colors_rgb', to='shop.ColorRGB', verbose_name='\u0426\u0432\u0435\u0442 RGB'),
        ),
        migrations.AddField(
            model_name='categorysinonim',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Category', verbose_name=b'\xd0\x9a\xd0\xb0\xd1\x82\xd0\xb5\xd0\xb3\xd0\xbe\xd1\x80\xd0\xb8\xd1\x8f'),
        ),
        migrations.AddField(
            model_name='branddescription',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Brand', verbose_name='\u0411\u0440\u0435\u043d\u0434'),
        ),
        migrations.AddField(
            model_name='branddescription',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Category', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f'),
        ),
        migrations.AddField(
            model_name='articles',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Category', verbose_name=b'\xd0\x9a\xd0\xb0\xd1\x82\xd0\xb5\xd0\xb3\xd0\xbe\xd1\x80\xd0\xb8\xd1\x8f'),
        ),
        migrations.AddField(
            model_name='category',
            name='properties',
            field=models.ManyToManyField(blank=True, null=True, to='shop.Property', verbose_name='\u0421\u0432\u043e\u0439\u0441\u0442\u0432\u0430'),
        ),
        migrations.AddField(
            model_name='order',
            name='color',
            field=models.ManyToManyField(through='shop.OrderColor', to='shop.ColorProduct', verbose_name='\u0426\u0432\u0435\u0442\u0430'),
        ),
        migrations.AddField(
            model_name='product',
            name='categorysinonim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorysinonim', to='shop.CategorySinonim', verbose_name='\u0421\u0438\u043d\u043e\u043d\u0438\u043c \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438'),
        ),
        migrations.AddField(
            model_name='product',
            name='rgb',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_rgb', to='shop.ColorRGB', verbose_name='\u0426\u0432\u0435\u0442 RGB'),
        ),
        migrations.AlterUniqueTogether(
            name='filterseo',
            unique_together=set([('category', 'slug')]),
        ),
    ]
