# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-04 11:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0047_auto_20170404_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='allprice',
            field=models.IntegerField(default=0, verbose_name='\u0426\u0435\u043d\u0430'),
        ),
        migrations.AlterField(
            model_name='ecomerce',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 4, 14, 37, 10, 722520), verbose_name=b'\xd0\x94\xd0\xb0\xd1\x82\xd0\xb0 \xd0\xbf\xd1\x83\xd0\xb1\xd0\xbb\xd0\xb8\xd0\xba\xd0\xb0\xd1\x86\xd0\xb8\xd0\xb8'),
        ),
        migrations.AlterField(
            model_name='ecomerceposition',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 4, 14, 37, 10, 724913), verbose_name=b'\xd0\x94\xd0\xb0\xd1\x82\xd0\xb0 \xd0\xbf\xd1\x83\xd0\xb1\xd0\xbb\xd0\xb8\xd0\xba\xd0\xb0\xd1\x86\xd0\xb8\xd0\xb8'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 4, 14, 37, 10, 702111), verbose_name=b'\xd0\x94\xd0\xb0\xd1\x82\xd0\xb0 \xd0\xbf\xd1\x83\xd0\xb1\xd0\xbb\xd0\xb8\xd0\xba\xd0\xb0\xd1\x86\xd0\xb8\xd0\xb8'),
        ),
        migrations.AlterField(
            model_name='product',
            name='action_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 4, 14, 37, 10, 687523), null=True, verbose_name=b'\xd0\x94\xd0\xb0\xd1\x82\xd0\xb0 \xd0\xbe\xd0\xba\xd0\xb0\xd0\xbd\xd1\x87\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5 \xd0\xb0\xd0\xba\xd1\x86\xd0\xb8\xd0\xb8'),
        ),
        migrations.AlterField(
            model_name='quikorder',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 4, 14, 37, 10, 712878), verbose_name=b'\xd0\x94\xd0\xb0\xd1\x82\xd0\xb0 \xd0\xbf\xd1\x83\xd0\xb1\xd0\xbb\xd0\xb8\xd0\xba\xd0\xb0\xd1\x86\xd0\xb8\xd0\xb8'),
        ),
        migrations.AlterField(
            model_name='statistica',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 4, 14, 37, 10, 720675), verbose_name=b'\xd0\x94\xd0\xb0\xd1\x82\xd0\xb0 \xd0\xbf\xd1\x83\xd0\xb1\xd0\xbb\xd0\xb8\xd0\xba\xd0\xb0\xd1\x86\xd0\xb8\xd0\xb8'),
        ),
    ]
