# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-05 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0050_auto_20170405_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='filters',
            field=models.ManyToManyField(blank=True, to='shop.Filter', verbose_name='\u0424\u0438\u043b\u044c\u0442\u0440\u044b'),
        ),
        migrations.AlterField(
            model_name='category',
            name='properties',
            field=models.ManyToManyField(blank=True, to='shop.Property', verbose_name='\u0421\u0432\u043e\u0439\u0441\u0442\u0432\u0430'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dopcategory',
            field=models.ManyToManyField(blank=True, related_name='dopcategory', to='shop.Category', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438'),
        ),
        migrations.AlterField(
            model_name='product',
            name='extraproduct',
            field=models.ManyToManyField(related_name='extra', to='shop.Product', verbose_name='\u0414\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0435 \u043f\u0440\u043e\u0434\u0443\u043a\u0442\u044b'),
        ),
        migrations.AlterField(
            model_name='product',
            name='giftproduct',
            field=models.ManyToManyField(related_name='gift', to='shop.Product', verbose_name='\u041f\u043e\u0434\u0430\u0440\u043a\u0438 \u043a \u043f\u0440\u043e\u0434\u0443\u043a\u0442\u0443'),
        ),
        migrations.AlterField(
            model_name='product',
            name='recomendproduct',
            field=models.ManyToManyField(related_name='recomend', to='shop.Product', verbose_name='\u0420\u0435\u043a\u043e\u043c\u0435\u043d\u0434\u043e\u0432\u0430\u0435\u043d\u043d\u044b\u0435  \u043f\u0440\u043e\u0434\u0443\u043a\u0442\u044b'),
        ),
        migrations.AlterField(
            model_name='uproduct',
            name='old_id',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=b'old_id'),
        ),
    ]
