# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-06 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0051_auto_20170405_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorproduct',
            name='name',
            field=models.CharField(blank=True, default=b'0', max_length=250, verbose_name='\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='product',
            name='extraproduct',
            field=models.ManyToManyField(blank=True, related_name='extra', to='shop.Product', verbose_name='\u0414\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0435 \u043f\u0440\u043e\u0434\u0443\u043a\u0442\u044b'),
        ),
        migrations.AlterField(
            model_name='product',
            name='giftproduct',
            field=models.ManyToManyField(blank=True, related_name='gift', to='shop.Product', verbose_name='\u041f\u043e\u0434\u0430\u0440\u043a\u0438 \u043a \u043f\u0440\u043e\u0434\u0443\u043a\u0442\u0443'),
        ),
        migrations.AlterField(
            model_name='product',
            name='recomendproduct',
            field=models.ManyToManyField(blank=True, related_name='recomend', to='shop.Product', verbose_name='\u0420\u0435\u043a\u043e\u043c\u0435\u043d\u0434\u043e\u0432\u0430\u0435\u043d\u043d\u044b\u0435  \u043f\u0440\u043e\u0434\u0443\u043a\u0442\u044b'),
        ),
    ]
