# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-08 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0053_noorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='noorder',
            name='producttext',
            field=models.CharField(default='', max_length=250, verbose_name=b'\xd0\xa2\xd0\xb5\xd0\xbb\xd0\xb5\xd1\x84\xd0\xbe\xd0\xbd'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quikorder',
            name='producttext',
            field=models.CharField(default='', max_length=250, verbose_name=b'\xd0\xa2\xd0\xb5\xd0\xbb\xd0\xb5\xd1\x84\xd0\xbe\xd0\xbd'),
            preserve_default=False,
        ),
    ]
