# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-29 08:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0055_auto_20170424_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorproduct',
            name='lastscan',
            field=models.TextField(blank=True, null=True, verbose_name=b'Lastscan'),
        ),
        migrations.AddField(
            model_name='colorproduct',
            name='lastscan_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 29, 11, 27, 26, 293399), verbose_name=b'Lastsscan Date'),
        ),
        migrations.AddField(
            model_name='colorproduct',
            name='price_rrc',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, null=True, verbose_name=b'\xd0\xa6\xd0\xb5\xd0\xbd\xd0\xb0 \xd0\xa0\xd0\xa0\xd0\xa6'),
        ),
        migrations.AddField(
            model_name='colorproduct',
            name='price_rrc_ok',
            field=models.BooleanField(default=False, verbose_name=b'Price rrc OK'),
        ),
    ]
