# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-29 08:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0057_auto_20170429_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concurent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name=b'\xd0\x9d\xd0\xb0\xd0\xb7\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5')),
                ('url', models.CharField(max_length=250, verbose_name=b'Url')),
                ('itemid', models.IntegerField(default=0, verbose_name=b'itemid')),
                ('pub_date', models.DateField(blank=True, default=datetime.date.today, verbose_name=b'\xd0\x94\xd0\xb0\xd1\x82\xd0\xb0 \xd0\xbf\xd1\x83\xd0\xb1\xd0\xbb\xd0\xb8\xd0\xba\xd0\xb0\xd1\x86\xd0\xb8\xd0\xb8')),
            ],
            options={
                'verbose_name': '\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0444\u0438\u0440\u043c\u044b',
                'verbose_name_plural': '\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0444\u0438\u0440\u043c',
            },
        ),
        migrations.AlterField(
            model_name='colorproduct',
            name='lastscan_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 29, 11, 36, 31, 743190), verbose_name=b'Lastsscan Date'),
        ),
        migrations.AddField(
            model_name='colorproduct',
            name='concurents',
            field=models.ManyToManyField(blank=True, null=True, to='shop.Concurent', verbose_name=b'\xd0\x9a\xd0\xbe\xd0\xbd\xd0\xba\xd1\x83\xd1\x80\xd0\xb5\xd0\xbd\xd1\x82\xd1\x8b'),
        ),
    ]
