# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-29 13:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0058_auto_20170429_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='lastscan_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name=b'\xd0\x94\xd0\xb0\xd1\x82\xd0\xb0 \xd0\xbe\xd0\xba\xd0\xb0\xd0\xbd\xd1\x87\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5 \xd0\xb0\xd0\xba\xd1\x86\xd0\xb8\xd0\xb8'),
        ),
        migrations.AlterField(
            model_name='colorproduct',
            name='lastscan_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 29, 16, 40, 12, 30979), verbose_name=b'Lastsscan Date'),
        ),
    ]
