# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-01 13:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0059_auto_20170429_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorproduct',
            name='lastscan_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 1, 16, 27, 19, 510234), verbose_name=b'Lastsscan Date'),
        ),
    ]
