# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-01 13:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0060_auto_20170501_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorproduct',
            name='lastscan_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 1, 16, 34, 21, 425052), verbose_name=b'Lastsscan Date'),
        ),
    ]
