# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-10 06:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0061_auto_20170501_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='concurent',
            name='strong',
            field=models.BooleanField(default=False, verbose_name=b'\xd0\x9e\xd0\xb1\xd1\x8f\xd0\xb7\xd0\xb0\xd1\x82\xd0\xb5\xd0\xbb\xd0\xb5\xd0\xbd'),
        ),
        migrations.AlterField(
            model_name='colorproduct',
            name='lastscan_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 10, 9, 46, 25, 345275), verbose_name=b'Lastsscan Date'),
        ),
    ]
