# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-10 13:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0062_auto_20170610_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorproduct',
            name='lastscan_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 10, 16, 23, 19, 268022), verbose_name=b'Lastsscan Date'),
        ),
    ]
