# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-26 07:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0063_auto_20170610_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='hotlineurl',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name=b'Hotline url'),
        ),
        migrations.AlterField(
            model_name='colorproduct',
            name='lastscan_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 26, 10, 15, 53, 286167), verbose_name=b'Lastsscan Date'),
        ),
    ]
