# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-20 08:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0064_auto_20170626_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ancor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancor', models.CharField(max_length=250, verbose_name=b'\xd0\x90\xd0\xbd\xd0\xba\xd0\xbe\xd1\x80')),
                ('url', models.CharField(max_length=250, verbose_name=b'\xd0\xa3\xd1\x80\xd0\xbb')),
                ('published', models.BooleanField(default=False, verbose_name=b'\xd0\x9e\xd0\xbf\xd1\x83\xd0\xb1\xd0\xbb\xd0\xb8\xd0\xba\xd0\xbe\xd0\xb2\xd0\xb0\xd0\xbd')),
            ],
        ),
        migrations.AlterField(
            model_name='colorproduct',
            name='lastscan_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 20, 10, 17, 4, 413190), verbose_name=b'Lastsscan Date'),
        ),
    ]
