# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-20 10:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0065_auto_20171120_1017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ancor',
            options={'verbose_name': '\u0410\u043d\u043a\u043e\u0440\u044b', 'verbose_name_plural': '\u0410\u043d\u043a\u043e\u0440\u044b'},
        ),
        migrations.AlterField(
            model_name='colorproduct',
            name='lastscan_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 20, 12, 57, 48, 312256), verbose_name=b'Lastsscan Date'),
        ),
    ]
