# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-09 08:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='menuitem',
            managers=[
            ],
        ),
    ]
