# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-10 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_article_disallow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='disallow',
            field=models.BooleanField(default=False, verbose_name=b'\xd0\x9d\xd0\xb5 \xd0\xb8\xd0\xbd\xd0\xb4\xd0\xb5\xd0\xba\xd1\x81\xd0\xb8\xd1\x80\xd0\xbe\xd0\xb2\xd0\xb0\xd1\x82\xd1\x8c'),
        ),
    ]
