# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-26 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20161210_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='overflow',
            field=models.BooleanField(default=False, verbose_name=b'\xd0\x9f\xd0\xb5\xd1\x80\xd0\xb5\xd0\xbe\xd0\xbf\xd1\x80\xd0\xb5\xd0\xb4\xd0\xb5\xd0\xbb\xd0\xb8\xd1\x82\xd1\x8c \xd0\xba\xd0\xbe\xd0\xbd\xd1\x82\xd0\xb5\xd0\xb9\xd0\xbd\xd0\xb5\xd1\x80\xd0\xbe\xd0\xb2'),
            preserve_default=False,
        ),
    ]
