# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-27 09:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20161227_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 12, 27, 9, 26, 7, 605279, tzinfo=utc), verbose_name=b'\xd0\x94\xd0\xb0\xd1\x82\xd0\xb0 \xd0\xbf\xd1\x83\xd0\xb1\xd0\xbb\xd0\xb8\xd0\xba\xd0\xb0\xd1\x86\xd0\xb8\xd0\xb8'),
        ),
        migrations.AlterField(
            model_name='snipet',
            name='text',
            field=redactor.fields.RedactorField(blank=True, verbose_name=b'\xd0\x9a\xd0\xbe\xd0\xb4 \xd1\x81\xd0\xbd\xd0\xb8\xd0\xbf\xd0\xb5\xd1\x82\xd0\xb0'),
        ),
    ]
